### ISSUE TITLE
Some characters are removed

### ISSUE THREAD

**Issue by WilliamHolmes** [blakeembrey/title-case#10]
Similar to issue to https://github.com/blakeembrey/title-case/issues/3

title-case `2.1.1`

### Use Case
We are showing peoples displayNames in the UI, in some cases the directories have stored these names as UPPERCASE.
Where this was the case, we were hoping to use title-case to make the displayNames more presentable.

We have noticed that in some names, characters are removed.

### Example
string > `john O' connor`

expected (or hoped for) > `John O' Connor`

result > `John O Connor`

**Comment by hdpinto** [comment]
If you read through the comments on that one, the author doesn't seem interested in fixing what is an obvious bug. This package (and literally every other "title-case" package that doesn't localize) is poorly-named. This is not "title case" behavior, it's "capitalize" behavior.

The suggestion was to use this instead:
https://www.npmjs.com/package/titlecase

**Comment by blakeembrey** [comment]
As mentioned in #3, this isn't something this module is currently used for. If there's a specific AP casing functionality you'd like, feel free to submit a PR. As I mentioned already in your linked issue, if someone wants to submit a PR and change the functionality, go for it. Someone just has to do it, because I have no desire to maintain proper AP casing functionality - it's subjective and tricky to please everything on a module like that. If it's purely a "whitelist", I'm also happy to accept a PR on that - though it should be to `no-case`. A white list feature is certainly a good PR, though it'll 100% fall short of AP casing functionality.

@hdpinto Although I appreciate your input, I don't appreciate the tone. It's not an "obvious bug", it's an out of scope feature. If you'd like to do a better job, submit a PR and maintain it. I don't have any desire to maintain the level of functionality being proposed so it'd only be detrimental to have me be the one to write it.

**Comment by blakeembrey** [comment]
There's also `titleize` which is incredibly simple also: https://github.com/sindresorhus/titleize/blob/master/index.js#L7-L9. I'd also recommend something like that, it really depends on your application at this point - not one thing will make everyone happy.
